/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejeextguia2;

/**
 *
 * @author Altamirano
 */
public class ListaDeTareas extends javax.swing.JFrame {

    
    /**
     * Creates new form ListaDeTareas
     */
    public ListaDeTareas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPpantalla = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jBcargarTarea = new javax.swing.JButton();
        jTnuevaTarea = new javax.swing.JTextField();
        jBtareasPendientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        jDPpantalla.setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Lista de tareas");

        jBcargarTarea.setText("cargar tarea");

        jTnuevaTarea.setText("ingrese tarea nueva");

        jBtareasPendientes.setText("ver tareas pendientes");
        jBtareasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtareasPendientesActionPerformed(evt);
            }
        });

        jDPpantalla.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPpantalla.setLayer(jBcargarTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPpantalla.setLayer(jTnuevaTarea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPpantalla.setLayer(jBtareasPendientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDPpantallaLayout = new javax.swing.GroupLayout(jDPpantalla);
        jDPpantalla.setLayout(jDPpantallaLayout);
        jDPpantallaLayout.setHorizontalGroup(
            jDPpantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPpantallaLayout.createSequentialGroup()
                .addGroup(jDPpantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDPpantallaLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jBcargarTarea)
                        .addGap(18, 18, 18)
                        .addComponent(jTnuevaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDPpantallaLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDPpantallaLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jBtareasPendientes)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jDPpantallaLayout.setVerticalGroup(
            jDPpantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPpantallaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDPpantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnuevaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcargarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jBtareasPendientes)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPpantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPpantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    

    private void jBtareasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtareasPendientesActionPerformed
               
        
        Tareas pantallaTarea = new Tareas();
        
        pantallaTarea.setVisible(true);
        jDPpantalla.add(pantallaTarea);
        jDPpantalla.moveToFront(pantallaTarea);
        
        
    }//GEN-LAST:event_jBtareasPendientesActionPerformed
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcargarTarea;
    private javax.swing.JButton jBtareasPendientes;
    private javax.swing.JDesktopPane jDPpantalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTnuevaTarea;
    // End of variables declaration//GEN-END:variables
}
